version: '2.2'
services:
  db:
    image: mysql:latest
    cpu_percent: 25
    env_file:
      - xt/env
    ports:
      - "33061:3306"
  web:
    image: alexcheng/magento2
    cpu_percent: 25
    env_file:
      - xt/env
    ports:
      - "80:80"
    links:
      - db:mysql
  rakudo:
    image: rakudo-star
    cpu_percent: 25
    links:
      - web
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
