#!/bin/bash

# rebuild / bring up all the instances (we have a third one now running rakudo)
docker-compose up --build -d;

# Setup magento / sample data
./scripts/magento-post-configuration;

# install my module dependencies and run xt tests
./scripts/perl6-Magento-tests
